name: Run Car Complaints Web Scraping Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC
  workflow_dispatch:      # optional manual trigger

env:
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
  PG_HOST: ${{ secrets.PG_HOST }}
  PG_DB: ${{ secrets.PG_DB }}

jobs:
  web-scrape:
    name: Extract and Load Car Complaints Data
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Car Complaints Web Scraper
        run: |
          python notebooks/Car_Complaints__Web_Scrape_Extract_Load_Raw.py