name: Run NHTSA API Pipeline

on:
  schedule:
    - cron: '0 12 * * *'  # runs daily at noon UTC (offset from web scraper)
  workflow_dispatch:      # optional manual trigger

env:
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
  PG_HOST: ${{ secrets.PG_HOST }}
  PG_DB: ${{ secrets.PG_DB }}

jobs:
  api-extract:
    name: Extract and Load NHTSA Recall Data
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run NHTSA API Data Extraction
        run: |
          python notebooks/NHTSA_API_Extract_Load_Raw.py